name: base_wallet
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.2
  get_it: ^7.2.0
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15
  retrofit: ^3.0.2
  flutter_svg: ^1.1.5
  dartz: ^0.10.1
  dio: ^4.0.6
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  web3dart: 2.3.5
  erc20: ^1.0.0
  eip55: ^1.0.2
  recase: ^4.1.0
  intl: ^0.17.0
  focus_detector: ^2.0.1
  decimal: ^2.3.0
  mobile_scanner: ^2.0.0
  flutter_secure_storage: ^6.0.0
  equatable: ^2.0.5
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
  go_router: ^5.0.5

dependency_overrides:
  analyzer: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  flutter_flavorizr: ^2.1.4
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.1
  retrofit_generator: ^4.1.2
  dart_code_metrics: ^4.19.1
  change_app_package_name: ^1.1.0
  isar_generator: ^3.0.2

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/
    - assets/networks/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flavorizr:
  app:
    android:
      flavorDimensions: "SleeFi"
    ios:

  instructions:
    - assets:download
    - assets:extract
    - android:androidManifest
    - android:buildGradle
    #    - android:dummyAssets
    - android:icons
    #- flutter:flavors
    #- flutter:app
    #- flutter:pages
    #- flutter:targets
    - ios:xcconfig
    - ios:buildTargets
    - ios:schema
    - ios:dummyAssets
    #    - ios:icons
    - ios:plist
    - ios:launchScreen
    #    - google:firebase
    - assets:clean
    - ide:config

  flavors:
    dev:
      app:
        name: "Wallet Dev"

      android:
        applicationId: "com.sotatek.wallet_base.dev"
      ios:
        bundleId: "com.sotatek.wallet-base.dev"

    stg:
      app:
        name: "Wallet Stg"

      android:
        applicationId: "com.sotatek.wallet_base.stg"
      ios:
        bundleId: "com.sotatek.wallet-base.stg"

    prod:
      app:
        name: "Wallet"

      android:
        applicationId: "com.sotatek.wallet_base"
      ios:
        bundleId: "com.sotatek.wallet-base"
